### ISSUE TITLE
how to use this mod I'm dumb

### ISSUE THREAD

**Issue by Keith1R0blox** [Ziegenhainy/XXLify#13]
yes I know this isn't a bug report or a feature suggestion but how to use it

**Comment by Ziegenhainy** [comment]
you go to any level longer than 4 minutes and it should show you a larger label.
you can customize the settings in the settings of geode

**Comment by Keith1R0blox** [comment]
I made my own level (not uploaded yet) and is there still a way how to do it?

**Comment by Keith1R0blox** [comment]
I thought it would just expand the level length in the editor

**Comment by Ziegenhainy** [comment]
> I thought it would just expand the level length in the editor

right now the mod only works on published levels
