### ISSUE TITLE
Certain levels do not show XXL tags.

### ISSUE THREAD

**Issue by OM3GA6400** [Ziegenhainy/XXLify#2]
![image](https://github.com/Ziegenhainy/XXLify/assets/98067930/bd410be2-7a6f-40bb-9b06-ce60ca603dee)

**Comment by Ziegenhainy** [comment]
this is the case with all 2.1 levels. there is no easy way to get the level time for those levels, so for the initial release I didnt.

**Comment by OM3GA6400** [comment]
you could probably just use the same method that bi uses or just require people to have bi installed than fetch directly from it

**Comment by Ziegenhainy** [comment]
> you could probably just use the same method that bi uses or just require people to have bi installed than fetch directly from it

yeah, that is probably what Ill end up doing. Altho making a dependency seems unnecessary and copying code feels like stealing to me.
